FROM centos:centos6

USER root
WORKDIR /

RUN yum install -y rpmdevtools make git
RUN rpmdev-setuptree

ENV GOROOT=/usr/local/go
ENV GOPATH=/root/.go
ENV PATH $GOROOT/bin:$PATH
ARG GO_VERSION=1.8.3
RUN wget -O- -q https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz | tar zxf - && \
    mv go /usr/local/
RUN mkdir $GOPATH
